# Problem
# A matrix is a rectangular table of values divided into rows and columns. An m×n matrix 
# has m rows and n columns. Given a matrix A, we write Ai,j to indicate the value found 
# at the intersection of row i and column j.
#
# Say that we have a collection of DNA strings, all having the same length n. Their profile 
# matrix is a 4×n matrix P in which P1,j represents the number of times that 'A' occurs in 
# the jth position of one of the strings, P2,j represents the number of times that C occurs 
# in the jth position, and so on (see below).
# 
# A consensus string c is a string of length n formed from our collection by taking the most 
# common symbol at each position; the jth symbol of c therefore corresponds to the symbol having 
# the maximum value in the j-th column of 
# the profile matrix. Of course, there may be more than one most common symbol, leading to multiple 
# possible consensus strings.
#
# DNA Strings
# A T C C A G C T
# G G G C A A C T
# A T G G A T C T
# A A G C A A C C
# T T G G A A C T
# A T G C C A T T
# A T G G C A C T
#
# Profile	
# A   5 1 0 0 5 5 0 0
# C   0 0 1 4 2 0 6 1
# G   1 1 6 3 0 1 0 0
# T   1 5 0 0 0 1 1 6
#
# Consensus	A T G C A A C T
# Given: A collection of at most 10 DNA strings of equal length (at most 1 kbp) in FASTA format.
#
# Return: A consensus string and profile matrix for the collection. (If several possible consensus 
# strings exist, then you may return any one of them.)


# ###################
# #### LIBRARIES ####
# ###################
library(Biostrings)


# ###################
# #### CONSTANTS ####
# ###################
DEFAULT_FILE_PATH <- "/Bioinformatics/Strings/0007 consensus_profile/"

A <- 65
C <- 67
G <- 71
T <- 84

A_OFFSET <- 64
C_OFFSET <- 65
G_OFFSET <- 68
T_OFFSET <- 80

LETTER_OFFSET <- c(1:T)*0
LETTER_OFFSET[A] <- A_OFFSET
LETTER_OFFSET[C] <- C_OFFSET
LETTER_OFFSET[G] <- G_OFFSET
LETTER_OFFSET[T] <- T_OFFSET

NUCLEOTIDE_NUMERIC <- c(A, C, G, T)


# ###################
# #### VARIABLES ####
# ###################
consensusFile <- NULL
outConsensus  <- c()


# ###################
# #### FUNCTIONS ####
# ###################

# #### I/O FUNCTIONS ####
# readInput
#   Access: private
readInput <- function(inputSource) {
  
  if (is.null(inputSource))
    return(NULL)
  
  wd <- getwd()
  input_filePath <- paste0(wd, DEFAULT_FILE_PATH, inputSource)  
  
  dna <- readDNAStringSet(input_filePath)
  return(dna)
  
}  # END readInput

# createConsensusOutput
#   Access: private
createConsensusOutput <- function() {

  wd <- getwd()
  output_filePath <<- paste0(wd, DEFAULT_FILE_PATH, "consensus.txt")
  consensusFile   <<- file(output_filePath, open = "wt")
  
}  # END createConsensusOutput

# writeConsensusOutput
#   Access: private
writeConsensusOutput <- function(newDnaString) {

  writeLines(newDnaString, consensusFile)
  
}  # END writeConsensusOutput

# destroyConsensusOutput
#   Access: private
destroyConsensusOutput <- function() {

  close(consensusFile)
  
}  # END destroyConsensusOutput


# #### PROFILE FUNCTIONS ####
# computeProfile
#   Access: private
computeProfile <- function(dna) {
  
  dna_number_table <- data.frame()

  for (idx in 1:length(dna)) {
    dna_nbr <- utf8ToInt(as.character(dna[[idx]]))
    dna_number_table <- rbind(dna_number_table, c(dna_nbr)) 
  }
  
  profile <- data.frame(matrix(0, ncol = ncol(dna_number_table), nrow = 4))
  rownames(profile) <- c("A:", "C:", "G:", "T:")

  for (idx in 1:ncol(dna_number_table)) {
    
    profile_name <- paste0("nc.", idx)
    names(dna_number_table)[idx] <- profile_name
    names(profile)[idx] <- profile_name
  }
  
  for (col_idx in 1:ncol(dna_number_table)) {
    
    col_dna <- dna_number_table[,col_idx]
    
    for (j in 1:length(col_dna))
      profile[(col_dna[j] - LETTER_OFFSET[col_dna[j]]), col_idx] <- 
        (profile[(col_dna[j] - LETTER_OFFSET[col_dna[j]]), col_idx] + 1)
  }
  
  return(profile)
  
}  # END computeProfile

# getProfile
#   Access: public
getProfile <- function(inputSource) {
  
  if (is.null(inputSource))
    return(NULL)

  dna <- readInput(inputSource)
  return(computeProfile(dna))
  
}  # END getProfile


# #### CONSENSUS FUNCTIONS ####
# getOneConsensus
#   Access: public
getOneConsensus <- function(profile) {
  
  if (is.null(profile) || (ncol(profile) < 1))
    return(NULL)
  
  c <- c()
  
  for (i in 1 : ncol(profile)) {
    
    p <- profile[, i]
    q <- NUCLEOTIDE_NUMERIC[which(p == max(p))][1]
    c <- c(c, q)
    
  }  # END for
  
  return(intToUtf8(c))
  
}  # END getOneConsensus

# computeConsensus
#   Access: private
computeConsensus <- function(profile, colIdx) {
  
  if (colIdx > ncol(profile)) {
    
    newDnaString <- intToUtf8(outConsensus)
    writeConsensusOutput(newDnaString)

    print(newDnaString)

    if (length(outConsensus) > 1) outConsensus <<- outConsensus[1:(length(outConsensus)-1)]
    else outConsensus <<- c()
    
    return()
    
  }  # END if
  
  # get the next profile column as a vector
  column <- profile[,colIdx]
    
  # if the vector is all zeros, the tree cannot be constructed any further
  if (all(column == 0))
    stop(paste0("profile colIdx: ", colIdx, " is all zeros."))
    
  # get the indices of the nucleotides having the highest frequencies
  maxValueIndices <- which(column == max(column))
    
  maxVal <- max(column)
  maxValueIndices <- sapply(column, function(x) { if (x < maxVal) x <- -1 else x <- x })
    
  for (i in 1:length(maxValueIndices)) {
    
    if (maxValueIndices[i] < 0 ) next
    
    outConsensus <<- c(outConsensus, NUCLEOTIDE_NUMERIC[i])
    computeConsensus(profile, (colIdx+1))

  }  # END for
  
  if (length(outConsensus) > 1) outConsensus <<- outConsensus[1:(length(outConsensus)-1)]
  else outConsensus <<- c()
    
}  # END computeConsensus

# getConsensus
#   Access: public
getConsensus <- function(profile) {
  
  if (is.null(profile) || (nrow(profile) > 4) || (ncol(profile) < 1))
    return(NULL)

  createConsensusOutput()  

  outConsensus  <<- c()
  computeConsensus(profile, 1)
  
  destroyConsensusOutput()
  
}  # END getConsensus


# ###################
# ##### TESTING #####
# ###################

# testGetConsensus
#   Access: public
testGetConsensus <- function(profile) {
  
  t0 <- Sys.time()
  getConsensus(profile)
  t1 <- Sys.time()
  
  print(t1-t0)
  
}  # END testGetConsensus

# computeNumDnaCombinations
# Access: public
computeNumDnaCombinations <-function(profile) {
  
  numDnaCombinations <- 1
  
  for (idx in 1:ncol(profile)) {
    
    # get the next profile column as a vector
    column <- profile[,idx]
    
    # get the indices of the nucleotides having the highest frequencies
    maxValueIndices <- which(column == max(column))
    
    numDnaCombinations <- (numDnaCombinations * length(maxValueIndices))
    
  }  # END for
  
  return(numDnaCombinations)
  
}  # END computeNumDnaCombinations


# #### BY-HAND TESTING ####
# x <- c("CTGGCTGTCCGGAACTATGGGTCTCCTGAGGCGATTTTTAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGAGGCGATTTTTAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGAGGCGATTTTTAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGAGGCGATTTTTAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGAGGCGATTTTTAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGAGGCGATTTTTAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGAGGCGATTTTTAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGAGGCGATTTTTAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGAGGCGATTTTTATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGAGGCGATTTTTATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGAGGCGATTTTTATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGAGGCGATTTTTATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTAGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTAGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTAGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTAGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTAGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTAGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTAGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTAGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTAGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTAGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTAGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTAGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTATAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTATAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTATAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTATAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTATAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTATAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTATAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTATAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTATATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTATATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTATATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTATATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTTAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTTAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTTAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTTAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTTAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTTAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTTAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTTAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTTATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTTATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTTATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATCTTTATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTAGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTAGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTAGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTAGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTAGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTAGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTAGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTAGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTAGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTAGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTAGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTAGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTATAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTATAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTATAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTATAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTATAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTATAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTATAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTATAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTATATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTATATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTATATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTATATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTTAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTTAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTTAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTTAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTTAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTTAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTTAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTTAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTTATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTTATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTTATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCCATTTTTATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTAGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTAGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTAGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTAGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTAGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTAGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTAGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTAGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTAGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTAGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTAGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTAGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTATAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTATAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTATAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTATAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTATAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTATAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTATAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTATAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTATATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTATATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTATATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTATATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTTAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTTAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTTAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTTAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTTAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTTAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTTAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTTAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTTATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTTATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTTATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATCTTTATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTAGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTAGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTAGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTAGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTAGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTAGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTAGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTAGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTAGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTAGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTAGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTAGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTATAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTATAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTATAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTATAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTATAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTATAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTATAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTATAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTATATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTATATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTATATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTATATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTTAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTTAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTTAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTTAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTTAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTTAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTTAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTTAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTTATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTTATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTTATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGGGGCGATTTTTATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTAGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTAGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTAGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTAGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTAGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTAGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTAGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTAGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTAGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTAGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTAGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTAGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTATAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTATAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTATAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTATAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTATAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTATAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTATAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTATAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTATATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTATATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTATATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTATATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTTAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTTAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTTAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTTAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTTAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTTAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTTAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTTAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTTATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTTATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTTATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATCTTTATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTAGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTAGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTAGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTAGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTAGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTAGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTAGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTAGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTAGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTAGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTAGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTAGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTATAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTATAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTATAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTATAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTATAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTATAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTATAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTATAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTATATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTATATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTATATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTATATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTTAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTTAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTTAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTTAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTTAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTTAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTTAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTTAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTTATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTTATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTTATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCCATTTTTATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTAGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTAGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTAGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTAGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTAGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTAGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTAGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTAGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTAGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTAGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTAGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTAGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTATAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTATAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTATAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTATAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTATAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTATAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTATAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTATAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTATATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTATATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTATATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTATATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTTAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTTAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTTAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTTAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTTAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTTAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTTAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTTAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTTATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTTATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTTATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATCTTTATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTAGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTAGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTAGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTAGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTAGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTAGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTAGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTAGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTAGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTAGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTAGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTAGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTATAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTATAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTATAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTATAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTATAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTATAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTATAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTATAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTATATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTATATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTATATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTATATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTTAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTTAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTTAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTTAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTTAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTTAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTTAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTTAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTTATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTTATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTTATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTGTGGCGATTTTTATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTAGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTAGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTAGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTAGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTAGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTAGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTAGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTAGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTAGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTAGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTAGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTAGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTATAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTATAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTATAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTATAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTATAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTATAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTATAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTATAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTATATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTATATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTATATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTATATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTTAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTTAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTTAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTTAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTTAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTTAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTTAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTTAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTTATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTTATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTTATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATCTTTATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTAGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTAGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTAGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTAGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTAGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTAGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTAGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTAGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTAGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTAGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTAGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTAGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTATAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTATAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTATAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTATAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTATAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTATAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTATAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTATAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTATATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTATATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTATATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTATATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTTAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTTAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTTAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTTAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTTAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTTAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTTAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTTAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTTATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTTATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTTATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCCATTTTTATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTAGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTAGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTAGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTAGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTAGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTAGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTAGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTAGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTAGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTAGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTAGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTAGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTATAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTATAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTATAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTATAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTATAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTATAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTATAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTATAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTATATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTATATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTATATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTATATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTTAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTTAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTTAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTTAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTTAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTTAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTTAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTTAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTTATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTTATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTTATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATCTTTATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTAGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTAGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTAGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTAGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTAGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTAGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTAGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTAGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTAGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTAGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTAGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTAGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTATAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTATAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTATAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTATAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTATAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTATAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTATAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTATAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTATATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTATATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTATATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTATATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTTAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTTAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTTAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTTAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTTAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTTAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTTAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTTAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTTATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTTATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTTATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTAGGCGATTTTTATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTAGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTAGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTAGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTAGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTAGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTAGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTAGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTAGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTAGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTAGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTAGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTAGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTATAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTATAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTATAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTATAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTATAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTATAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTATAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTATAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTATATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTATATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTATATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTATATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTTAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTTAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTTAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTTAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTTAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTTAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTTAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTTAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTTATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTTATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTTATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATCTTTATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTAGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTAGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTAGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTAGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTAGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTAGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTAGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTAGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTAGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTAGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTAGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTAGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTATAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTATAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTATAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTATAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTATAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTATAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTATAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTATAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTATATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTATATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTATATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTATATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTTAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTTAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTTAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTTAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTTAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTTAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTTAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTTAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTTATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTTATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTTATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCCATTTTTATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTAGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTAGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTAGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTAGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTAGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTAGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTAGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTAGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTAGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTAGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTAGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTAGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTATAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTATAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTATAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTATAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTATAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTATAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTATAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTATAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTATATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTATATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTATATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTATATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTTAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTTAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTTAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTTAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTTAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTTAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTTAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTTAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTTATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTTATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTTATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATCTTTATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTAGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTAGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTAGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTAGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTAGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTAGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTAGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTAGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTAGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTAGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTAGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTAGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTATAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTATAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTATAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTATAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTATAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTATAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTATAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTATAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTATATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTATATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTATATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTATATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTTAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTTAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTTAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTTAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTTAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTTAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTTAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTTAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTTATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTTATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTTATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTGGGCGATTTTTATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTAGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTAGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTAGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTAGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTAGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTAGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTAGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTAGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTAGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTAGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTAGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTAGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTATAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTATAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTATAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTATAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTATAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTATAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTATAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTATAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTATATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTATATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTATATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTATATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTTAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTTAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTTAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTTAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTTAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTTAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTTAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTTAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTTATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTTATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTTATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATCTTTATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTAGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTAGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTAGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTAGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTAGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTAGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTAGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTAGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTAGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTAGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTAGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTAGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTATAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTATAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTATAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTATAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTATAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTATAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTATAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTATAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTATATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTATATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTATATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTATATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTTAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTTAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTTAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTTAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTTAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTTAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTTAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTTAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTTATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTTATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTTATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCCATTTTTATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTAGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTAGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTAGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTAGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTAGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTAGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTAGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTAGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTAGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTAGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTAGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTAGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTATAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTATAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTATAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTATAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTATAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTATAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTATAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTATAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTATATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTATATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTATATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTATATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTTAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTTAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTTAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTTAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTTAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTTAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTTAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTTAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTTATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTTATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTTATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATCTTTATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTAGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTAGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTAGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTAGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTAGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTAGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTAGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTAGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTAGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTAGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTAGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTAGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTATAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTATAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTATAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTATAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTATAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTATAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTATAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTATAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTATATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTATATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTATATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTATATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTGAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTGAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTGAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTGAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTGATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTGATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTGATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTGATGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTTAAGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTTAAGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTTAAGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTTAAGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTTAGGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTTAGGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTTAGGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTTAGGTCGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTTATGACGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTTATGACGT", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTTATGTCGC", "CTGGCTGTCCGGAACTATGGGTCTCCTTTGGCGATTTTTATGTCGT", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTAGAAGACGC", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTAGAAGACGT", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTAGAAGTCGC", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTAGAAGTCGT", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTAGAGGACGC", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTAGAGGACGT", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTAGAGGTCGC", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTAGAGGTCGT", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTAGATGACGC", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTAGATGACGT", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTAGATGTCGC", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTAGATGTCGT", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTATAAGACGC", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTATAAGACGT", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTATAAGTCGC", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTATAAGTCGT", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTATAGGACGC", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTATAGGACGT", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTATAGGTCGC", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTATAGGTCGT", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTATATGACGC", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTATATGACGT", "CTGGCTGTCCGGAACTATGGGTGGCCTGAGGCCATCTATATGTCGC")

# createConsensusOutput()
# writeConsensusOutput("CTGGCTGTCCGGAACTATGGGTCTCCTGAGGCGATTTTTAAGACGC")
# writeConsensusOutput("CTGGCTGTCCGGAACTATGGGTCTCCTGAGGCGATTTTTAAGACGT")
# writeConsensusOutput("CTGGCTGTCCGGAACTATGGGTCTCCTGAGGCGATTTTTAAGTCGC")
# destroyConsensusOutput()

# testFile <- file(output_filePath, open = "r")
# readConsensus <- readLines(testFile)
# close(testFile)

#profile_t <- data.frame(matrix(0, ncol = 4, nrow = 4))
#rownames(profile_t) <- c("A", "C", "G", "T")
#colnames(profile_t) <- c("nc.1", "nc.2", "nc.3", "nc.4")
#
#profile_t[1, 1] <- 5
#profile_t[2, 1] <- 5
#profile_t[4, 2] <- 5
#profile_t[3, 3] <- 5
#profile_t[4, 3] <- 5
#profile_t[1, 4] <- 5
#profile_t[2, 4] <- 5
#profile_t[4, 4] <- 5
