# Problem
# A string is simply an ordered collection of symbols selected from some alphabet and formed into a word; 
# the length of a string is the number of symbols that it contains. An example of a length 21 DNA string 
# (whose alphabet contains the symbols 'A', 'C', 'G', and 'T') is "ATGCTTCAGAAAGGTCTTACG."
#
# Given: A DNA string s of length at most 1000 nt.
# Return: Four integers (separated by spaces) counting the respective number of times that the symbols 
# 'A', 'C', 'G', and 'T' occur in s.
# Sample Dataset
# AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC
# Sample Output
# 20 12 17 21

# numeric values for each letter (each representing a nucleobase)
A <- 65
C <- 67
G <- 71
T <- 84

ct <- integer(100)

# sample data
# s <- strsplit("AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC", split = "")

# test data
s <- strsplit("CTCCGCATCATATGTAGCGACCCGGGGTCCAAATCAACAGTATTAAATTCCACCTCTCTTTTGACCTATCATTTGCAGCTTTCAAATCACGTTCCGTCGAGATGTAAGCATCTTAGGGTCCATGCAGAATGCTACGAGCTCTGGACCAATAACCGTCCTACAGGCATCAAATGATAGAAGTTCCGCAAATTCCGTCTGAGGAGTATGAGGCACGCGCGTTAAGCCTCGCCGAGAACGACCGGTACTCATCTATACCAGGGGATTCCTAAGCCCGCACTACACCGACGGACGGGTCTACTGCCGGCAGTCGCTCCCCCGAAGTTCGTTGGAGAGCGGCGCCTACCTCTTTCTGAGTCATTGCATAGAGTGAGCGTCGTAGTAGCTCGTCGCTAGTCTATAAGCTCGATTGAATTCGCGCAACGCATACGAATCTGGGAGAAATGCGCCACTATCTTCTTCGTTGCTACGACAGGATCTGGGCTAACTGCCTGAAGTACATTCTACTGATGCTTTGATAGCCTGCTTGAAGCTGCCCCTTAGCCCCCACCTTGGCCTCGATAGGAGCGAAACGACCAGCTGTCGCCTCAACGTGTTGCGCGTCGAGTGTGATGACCCTCTACGTTCAGTGAATCGCCGTAATGTGGAAGCTCCAGGACTACCTATTGAAACTCACTATATAACATGATTCACATAATTAGCCATGCATACAGTTGAAAATTACGTCCGGTGTCCCAAGCATCTGGTTTAATCCTCGTCGCCACCTCGTCCCCTGGCCCTTGTCCAGTTCCCGGCCCGGAACTTGCCAAAGGTGAAGCCAATAACGCAACTTTACGGGGTGGTTCCAGCTTCATAAAATATTAGCTGCTTTTCGGGGGAACTGTCCTCCTCGAGAAGCGGTGTCACGGCACTCTATATTACATTTCTAGTATATAGAGAT", split = "")

startTime <- Sys.time()
for (idx in 1:length(s[[1]])) {
  hidx <- as.numeric(charToRaw(s[[1]][idx]))
  ct[hidx] <- (ct[hidx] + 1)
}
endTime <- Sys.time()

print(paste0(ct[A], " ", ct[C], " ", ct[G], " ", ct[T]))
print(endTime-startTime)
