# Problem
# A DNA string is a reverse palindrome if it is equal to its reverse complement. For instance, GCATGC 
# is a reverse palindrome because its reverse complement is GCATGC. See Figure 2.
#
# Given: A DNA string of length at most 1 kbp in FASTA format.
# 
# Return: The position and length of every reverse palindrome in the string having length between 4 and 12. 
# You may return these pairs in any order.

# A: 65, C: 67, G:71, T: 84

# debug
TEST <- FALSE

# dna substring lengths to compare: 4 - 12
MIN_COMP_LENGTH <- 4
MAX_COMP_LENGTH <- 12

# define array of nucleotide complements
complement <- vector(length = 84)
complement[65] <-  19
complement[84] <- -19
complement[67] <-  4
complement[71] <- -4

getNucleotideComplement <- function(x) {x + complement[x]}

startTime <- Sys.time()

# take input and convert letters to numbers
# dna <- "TCAATGCATGCGGGTCTATATGCAT"
# dna <- "GCGCGTCTCCACAAATACTTCGCATAGTAGTAACACGACATCGTTGCAAGAGCTGCCAGGTCTGTCGTTACAGTACATTTGGCCCTACTCATTGCTGGCATATCAACGTAAAATATACGAGCGAGCACACATTGATCGTCTACCTCGCACACCTTACCGAGAAGGGATGAAAATTAAAAGCATGGCGTTAATCTCGTCCAAGATTGATATCTCTGAGTTTTAGGGTTTACATAAAGGCGTTGTCCGACAACACACAGCACCCCTGCCTGATGTAAGGCAAAGTTCCATCTGGCGAGAAAGCGGGTCCCAGGCACCGGTATAGGACTTCTGCTTCGGCCCCAGTTTTCACAGGTATTGAAGAACTGCGCATTATCTCCCGGCAAGTGTGGTTTTGGCTTCATTAATAGTTGAGAGCTGAAAGAAGTGCGTACGCACACCTCGTCCGTCCGTTTGGCATAGGACCTCGGCTTTCTGACCTGTTGCCTGGTCTCGTGTATCTACAAAGGGCAGCGCGTTAGGTGCCAAGGGCGAGATTGCAATTTAGGCGAGGCACATACCCTTTGTATCCGTACGCTCGTGGCGGTGGAGCGTCACGGCGGTGAAAACGGCTCGACGCCATTGTCAAGAACATTTTAGGCCAGTGTTTGCGTGAGACAGTGGTCTTCGCTCCGATTTCTGTCTCTCCTGCTAACCTAAGTGAACGCCGGGTCTTAACACTGCGGAGGGGTAGTGAGCACGGAGACACTACGCGCACACCCAGCGCCGAGGCGGGCGAACCTTCTGCTTTACTCTGCGGACACCTCTCCGTTATCGAGCTAGACACCGCAATGGGAGAGGCGGGTGTCCCATCAACGGCGC"
# dna <- "GCGCGTCTCCACAAATACTTCGCATAGTAGTAACACGACATCGTTGCAAGAGCTGCCAGGTCTGTCGTTACAGTACATTTGGCCCTACTCATTGCTGGCATATCAACGTAAAATATACGAGCGAGCACACATTGATCGTCTACCTCGCACACCTTACCGAGAAGGGATGAAAATTAAAAGCATGGCGTTAATCTCGTCCAAGATTGATATCTCTGAGTTTTAGGGTTTACATAAAGGCGTTGTCCGACAACACACAGCACCCCTGCCTGATGTAAGGCAAAGTTCCATCTGGCGAGAAAGCGGGTCCCAGGCACCGGTATAGGACTTCTGCTTCGGCCCCAGTTTTCACAGGTATTGAAGAACTGCGCATTATCTCCCGGCAAGTGTGGTTTTGGCTTCATTAATAGTTGAGAGCTGAAAGAAGTGCGTACGCACACCTCGTCCGTCCGTTTGGCATAGGACCTCGGCTTTCTGACCTGTTGCCTGGTCTCGTGTATCTACAAAGGGCAGCGCGTTAGGTGCCAAGGGCGAGATTGCAATTTAGGCGAGGCACATACCCTTTGTATCCGTACGCTCGTGGCGGTGGAGCGTCACGGCGGTGAAAACGGCTCGACGCCATTGTCAAGAACATTTTAGGCCAGTGTTTGCGTGAGACAGTGGTCTTCGCTCCGATTTCTGTCTCTCCTGCTAACCTAAGTGAACGCCGGGTCTTAACACTGCGGAGGGGTAGTGAGCACGGAGACACTACGCGCACACCCAGCGCCGAGGCGGGCGAACCTTCTGCTTTACTCTGCGGACACCTCTCCGTTATCGAGCTAGACACCGCAATGGGAGAGGCGGGTGTCCCATCAACGGCGCGCGCGTCTCCACAAATACTTCGCATAGTAGTAACACGACATCGTTGCAAGAGCTGCCAGGTCTGTCGTTACAGTACATTTGGCCCTACTCATTGCTGGCATATCAACGTAAAATATACGAGCGAGCACACATTGATCGTCTACCTCGCACACCTTACCGAGAAGGGATGAAAATTAAAAGCATGGCGTTAATCTCGTCCAAGATTGATATCTCTGAGTTTTAGGGTTTACATAAAGGCGTTGTCCGACAACACACAGCACCCCTGCCTGATGTAAGGCAAAGTTCCATCTGGCGAGAAAGCGGGTCCCAGGCACCGGTATAGGACTTCTGCTTCGGCCCCAGTTTTCACAGGTATTGAAGAACTGCGCATTATCTCCCGGCAAGTGTGGTTTTGGCTTCATTAATAGTTGAGAGCTGAAAGAAGTGCGTACGCACACCTCGTCCGTCCGTTTGGCATAGGACCTCGGCTTTCTGACCTGTTGCCTGGTCTCGTGTATCTACAAAGGGCAGCGCGTTAGGTGCCAAGGGCGAGATTGCAATTTAGGCGAGGCACATACCCTTTGTATCCGTACGCTCGTGGCGGTGGAGCGTCACGGCGGTGAAAACGGCTCGACGCCATTGTCAAGAACATTTTAGGCCAGTGTTTGCGTGAGACAGTGGTCTTCGCTCCGATTTCTGTCTCTCCTGCTAACCTAAGTGAACGCCGGGTCTTAACACTGCGGAGGGGTAGTGAGCACGGAGACACTACGCGCACACCCAGCGCCGAGGCGGGCGAACCTTCTGCTTTACTCTGCGGACACCTCTCCGTTATCGAGCTAGACACCGCAATGGGAGAGGCGGGTGTCCCATCAACGGCGC"
dna <- "GCGCGTCTCCACAAATACTTCGCATAGTAGTAACACGACATCGTTGCAAGAGCTGCCAGGTCTGTCGTTACAGTACATTTGGCCCTACTCATTGCTGGCATATCAACGTAAAATATACGAGCGAGCACACATTGATCGTCTACCTCGCACACCTTACCGAGAAGGGATGAAAATTAAAAGCATGGCGTTAATCTCGTCCAAGATTGATATCTCTGAGTTTTAGGGTTTACATAAAGGCGTTGTCCGACAACACACAGCACCCCTGCCTGATGTAAGGCAAAGTTCCATCTGGCGAGAAAGCGGGTCCCAGGCACCGGTATAGGACTTCTGCTTCGGCCCCAGTTTTCACAGGTATTGAAGAACTGCGCATTATCTCCCGGCAAGTGTGGTTTTGGCTTCATTAATAGTTGAGAGCTGAAAGAAGTGCGTACGCACACCTCGTCCGTCCGTTTGGCATAGGACCTCGGCTTTCTGACCTGTTGCCTGGTCTCGTGTATCTACAAAGGGCAGCGCGTTAGGTGCCAAGGGCGAGATTGCAATTTAGGCGAGGCACATACCCTTTGTATCCGTACGCTCGTGGCGGTGGAGCGTCACGGCGGTGAAAACGGCTCGACGCCATTGTCAAGAACATTTTAGGCCAGTGTTTGCGTGAGACAGTGGTCTTCGCTCCGATTTCTGTCTCTCCTGCTAACCTAAGTGAACGCCGGGTCTTAACACTGCGGAGGGGTAGTGAGCACGGAGACACTACGCGCACACCCAGCGCCGAGGCGGGCGAACCTTCTGCTTTACTCTGCGGACACCTCTCCGTTATCGAGCTAGACACCGCAATGGGAGAGGCGGGTGTCCCATCAACGGCGCGCGCGTCTCCACAAATACTTCGCATAGTAGTAACACGACATCGTTGCAAGAGCTGCCAGGTCTGTCGTTACAGTACATTTGGCCCTACTCATTGCTGGCATATCAACGTAAAATATACGAGCGAGCACACATTGATCGTCTACCTCGCACACCTTACCGAGAAGGGATGAAAATTAAAAGCATGGCGTTAATCTCGTCCAAGATTGATATCTCTGAGTTTTAGGGTTTACATAAAGGCGTTGTCCGACAACACACAGCACCCCTGCCTGATGTAAGGCAAAGTTCCATCTGGCGAGAAAGCGGGTCCCAGGCACCGGTATAGGACTTCTGCTTCGGCCCCAGTTTTCACAGGTATTGAAGAACTGCGCATTATCTCCCGGCAAGTGTGGTTTTGGCTTCATTAATAGTTGAGAGCTGAAAGAAGTGCGTACGCACACCTCGTCCGTCCGTTTGGCATAGGACCTCGGCTTTCTGACCTGTTGCCTGGTCTCGTGTATCTACAAAGGGCAGCGCGTTAGGTGCCAAGGGCGAGATTGCAATTTAGGCGAGGCACATACCCTTTGTATCCGTACGCTCGTGGCGGTGGAGCGTCACGGCGGTGAAAACGGCTCGACGCCATTGTCAAGAACATTTTAGGCCAGTGTTTGCGTGAGACAGTGGTCTTCGCTCCGATTTCTGTCTCTCCTGCTAACCTAAGTGAACGCCGGGTCTTAACACTGCGGAGGGGTAGTGAGCACGGAGACACTACGCGCACACCCAGCGCCGAGGCGGGCGAACCTTCTGCTTTACTCTGCGGACACCTCTCCGTTATCGAGCTAGACACCGCAATGGGAGAGGCGGGTGTCCCATCAACGGCGCGCGCGTCTCCACAAATACTTCGCATAGTAGTAACACGACATCGTTGCAAGAGCTGCCAGGTCTGTCGTTACAGTACATTTGGCCCTACTCATTGCTGGCATATCAACGTAAAATATACGAGCGAGCACACATTGATCGTCTACCTCGCACACCTTACCGAGAAGGGATGAAAATTAAAAGCATGGCGTTAATCTCGTCCAAGATTGATATCTCTGAGTTTTAGGGTTTACATAAAGGCGTTGTCCGACAACACACAGCACCCCTGCCTGATGTAAGGCAAAGTTCCATCTGGCGAGAAAGCGGGTCCCAGGCACCGGTATAGGACTTCTGCTTCGGCCCCAGTTTTCACAGGTATTGAAGAACTGCGCATTATCTCCCGGCAAGTGTGGTTTTGGCTTCATTAATAGTTGAGAGCTGAAAGAAGTGCGTACGCACACCTCGTCCGTCCGTTTGGCATAGGACCTCGGCTTTCTGACCTGTTGCCTGGTCTCGTGTATCTACAAAGGGCAGCGCGTTAGGTGCCAAGGGCGAGATTGCAATTTAGGCGAGGCACATACCCTTTGTATCCGTACGCTCGTGGCGGTGGAGCGTCACGGCGGTGAAAACGGCTCGACGCCATTGTCAAGAACATTTTAGGCCAGTGTTTGCGTGAGACAGTGGTCTTCGCTCCGATTTCTGTCTCTCCTGCTAACCTAAGTGAACGCCGGGTCTTAACACTGCGGAGGGGTAGTGAGCACGGAGACACTACGCGCACACCCAGCGCCGAGGCGGGCGAACCTTCTGCTTTACTCTGCGGACACCTCTCCGTTATCGAGCTAGACACCGCAATGGGAGAGGCGGGTGTCCCATCAACGGCGCGCGCGTCTCCACAAATACTTCGCATAGTAGTAACACGACATCGTTGCAAGAGCTGCCAGGTCTGTCGTTACAGTACATTTGGCCCTACTCATTGCTGGCATATCAACGTAAAATATACGAGCGAGCACACATTGATCGTCTACCTCGCACACCTTACCGAGAAGGGATGAAAATTAAAAGCATGGCGTTAATCTCGTCCAAGATTGATATCTCTGAGTTTTAGGGTTTACATAAAGGCGTTGTCCGACAACACACAGCACCCCTGCCTGATGTAAGGCAAAGTTCCATCTGGCGAGAAAGCGGGTCCCAGGCACCGGTATAGGACTTCTGCTTCGGCCCCAGTTTTCACAGGTATTGAAGAACTGCGCATTATCTCCCGGCAAGTGTGGTTTTGGCTTCATTAATAGTTGAGAGCTGAAAGAAGTGCGTACGCACACCTCGTCCGTCCGTTTGGCATAGGACCTCGGCTTTCTGACCTGTTGCCTGGTCTCGTGTATCTACAAAGGGCAGCGCGTTAGGTGCCAAGGGCGAGATTGCAATTTAGGCGAGGCACATACCCTTTGTATCCGTACGCTCGTGGCGGTGGAGCGTCACGGCGGTGAAAACGGCTCGACGCCATTGTCAAGAACATTTTAGGCCAGTGTTTGCGTGAGACAGTGGTCTTCGCTCCGATTTCTGTCTCTCCTGCTAACCTAAGTGAACGCCGGGTCTTAACACTGCGGAGGGGTAGTGAGCACGGAGACACTACGCGCACACCCAGCGCCGAGGCGGGCGAACCTTCTGCTTTACTCTGCGGACACCTCTCCGTTATCGAGCTAGACACCGCAATGGGAGAGGCGGGTGTCCCATCAACGGCGC"

dna_nbr    <- utf8ToInt(dna)
dna_length <- length(dna_nbr)

if (TEST) print(dna_length)

# create results data frame
results <- data.frame(idx=0, len=0)
names(results) <- c("idx", "len")

for (idx in 1:dna_length) {
  
  if ((idx+MIN_COMP_LENGTH-1) > dna_length) {
    if (TEST) print("BREAK 001")
    break()
  }
  
  for (comp_length in MIN_COMP_LENGTH : MAX_COMP_LENGTH) {
    
    if (TEST) print(paste0("idx: ", idx))
    if (TEST) print(paste0("comp_length: ", comp_length))
    if (TEST) print("---")
    if (TEST) print(" ")
    
    if ((idx+comp_length-1) > dna_length) {
      if (TEST) print("BREAK!")
      if (TEST) print(" ")
      break();
    }
    
    p <- dna_nbr[idx:(idx+comp_length-1)]
    if (TEST) print(p)
    
    isPalindrome <- TRUE
    for (j in 1:length(p)) {
      
      if (TEST) print(paste0("P[", j, "]: ", p[j]))
      if (TEST) print(paste0("comp. idx: ", ((length(p)-j)+1)))
      if (TEST) print(paste0("comp nucleotide: " , getNucleotideComplement(p[((length(p)-j)+1)])))
      if (TEST) print("===")
      if (TEST) print(" ")
      
      if (p[j] != getNucleotideComplement(p[((length(p)-j)+1)])) {
      
        isPalindrome <- FALSE
        break()
        
      }  # END if
      
    }  # END for
      
    if (isPalindrome)
      results <- rbind(results, c(idx, comp_length))
    
  }  # END for
  
}  # END for

print("v3")
endTime <- Sys.time()
print(endTime - startTime)