# Problem
# An RNA string is a string formed from the alphabet containing 'A', 'C', 'G', and 'U'. Given a DNA 
# string t corresponding to a coding strand, its transcribed RNA string u is formed by replacing 
# all occurrences of 'T' in t with 'U' in u.
# 
# Given: A DNA string t having length at most 1000 nt.
# Return: The transcribed RNA string of t.
# Sample Dataset
# GATGGAACTTGACTACGTAAATT
# Sample Output
# GAUGGAACUUGACUACGUAAAUU
# sample dna data
# dna <- "GATGGAACTTGACTACGTAAATT"

# test dna data
# dna <- "CAACGGTATGTTAGGGTGTGGCCACTTGGCCAGTATTGTTTACACCTGTGAGGCCTAGGCTACATGTACTCCGATTTGGTGACCATTCCAGTGCAAGAACATCTGGTGTTACGAAATGTAGATGATCTTGGCGAAAAAGATTCAGCCTGTTAGATGTCTGACTGTGAATTACAAGACGTGCTGATTATGGGGGGCTATCGCGACTGTCGCCAATCAGCAGCCTGCGCACGCCTCACTCTTCCTCATACAATAGACGGGGGGGGCTCAGCAGGTTGTGTGTGCCGAGTGGTTGTAAACTAGCTTATAGTTACCCTCTGTGTGAAGTTGCCATCGGCCGTGAGGTACTTCAATACATTGAGGTAGGAGCACCACGCGAGGCGTGCCCTAAAGTGGCGAGAAGAGACCCGAGCACATAGTAGGCAAATCACAGGGCAAACGACGAGCTGAGGCTAATAGAAATCACAACACAACTGACTTAGTAGGTTTCATGCGCTCAGACCGTAAGAAGTACTCAATAGAAATCTGCTGTAGCGCGGCTCCTCCGATTGTTACACATGGCGTAATGGGAGTTTCTCCTAGTCATAGCCGTACACACACCTTAGGGCAGTCCTAACTTCTCACCAGCACGAGTAAATTTCTACGCACGGCGTAGCCGGGGTCCTAGCTTTGGACTATATTTTACTGTCTTGCAGGGAGATACTCACCACGTAAGGGCTCGACGTGTATTTCCTAGATCCCGATTTCAATCAGAAACGTACACTGTACCGTCAAGAGAGAATAGGAACAAAGAGCGAACCCTACCCGTAAGTGATATAACTGGAAGGACCAGACGCCACTTATCAAATTCGTTCTCGGACCTTAAAATCGTCAGAAGTCGGATTCACTTAGAGAAATTACCAGAGACTAATTTCAGGCAATTAAGGAAGAC"

transcribeDnaToRna <- function(dna) {
  
  rna <- gsub("T", "U", dna, ignore.case = FALSE, perl = FALSE, fixed = FALSE, useBytes = FALSE)
  return(rna)
  
}  # END transcribeDnaToRna


